# Base configs
baseurl: "https://nnamd.github.io/art_and_more"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Home Bakes by Nnamdi Nwagwu"
subtitle: "Some visual treats."
author: "Nnamdi Nwagwu"
header:
 title: "Home Bakes"
 subtitle: "by Nnamdi"
footer:
 name: "Hi my name is Nnamdi Nwagwu"
 bio: "I am a robotics engineer, home baker, and textile art enthusiast."
 github: "See my engineering work on <a href=\"https://nnamd.github.io\">my other website</a> :)"
web_design: "AJ"

social_urls:
  github: "https://www.github.com/nnamd"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'